(set-background-color "#f1e9f7")

(set-face-attribute 'default nil :font "DejaVu Sans Mono 10")
(set-face-attribute 'region nil :background "#6d916d" :foreground "white")
(set-face-attribute 'highlight nil :background "#9eb59e" :foreground "white")
(set-face-attribute 'mode-line nil :background "#9eb59e" :weight 'bold)
(set-face-attribute 'mode-line-buffer-id nil :background "#9eb59e" :foreground "black")
(set-face-attribute 'mode-line-highlight nil :background "#9eb59e" :foreground "white")
(set-face-attribute 'mode-line-inactive nil :background "#a6a6a6" :foreground "black" :weight 'bold)
(set-face-attribute 'fringe nil :foreground "white" :background "#9eb59e")
(set-face-attribute 'minibuffer-prompt nil :foreground "#6d916d")
(set-face-attribute 'link nil :foreground "#858ac7")
(set-face-attribute 'link-visited nil :foreground "#a1a4cc")

(set-frame-parameter nil 'alpha 98)

(window-divider-mode)
(set-face-foreground 'window-divider "#a6a6a6")

(set-face-foreground 'default "#3b3b3b")
(set-face-foreground 'font-lock-variable-name-face "#cab74c")
(set-face-foreground 'font-lock-string-face "#C78BA0")
(set-face-foreground 'font-lock-preprocessor-face "#1c46a8")
(set-face-foreground 'font-lock-type-face "#bc8f8f")
(set-face-foreground 'font-lock-constant-face "#1c46a8")
(set-face-foreground 'font-lock-keyword-face "#8B8DC7")
(set-face-foreground 'font-lock-builtin-face "#9c9bbf")
(set-face-foreground 'font-lock-function-name-face "#865faa")
(set-face-foreground 'font-lock-comment-face "#8b8386")
(set-face-foreground 'font-lock-warning-face "#cd2626")